import { fileURLToPath, URL } from "node:url";
import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    // Makes it installable as an app, on the PC (Chrome/Edge "Install") and on phones.
    VitePWA({
      registerType: "autoUpdate",
      // Icons come from pwa-assets.config.ts, generated by `bun run icons`.
      includeAssets: ["favicon.svg", "favicon.ico", "apple-touch-icon-180x180.png"],
      manifest: {
        name: "The Daily You",
        short_name: "Daily You",
        description: "A local AI diary that prints your day as a newspaper.",
        display: "standalone",
        start_url: "/chat",
        background_color: "#ffffff",
        theme_color: "#ffffff",
        icons: [
          { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
          { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
          { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
          { src: "maskable-icon-512x512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
        ],
      },
      workbox: {
        // Only the app itself is cached. Diary data always comes fresh from the server.
        globPatterns: ["**/*.{js,css,html,svg,png,ico,woff2}"],
        navigateFallbackDenylist: [/^\/api\//],
        importScripts: ["push-sw.js"],
      },
    }),
  ],
  resolve: {
    alias: { "@": fileURLToPath(new URL("./src", import.meta.url)) },
  },
  server: {
    port: 5173,
    // Forward API calls to the Bun server in dev.
    proxy: { "/api": process.env.API_URL ?? "http://127.0.0.1:3000" },
  },
});
